# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workingGui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import copy

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 50, 331, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frameLabel = QtWidgets.QLabel(self.frame)
        self.frameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.frameLabel.setObjectName("frameLabel")
        self.horizontalLayout_3.addWidget(self.frameLabel)
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_3.addWidget(self.line_6)
        self.pidLabel = QtWidgets.QLabel(self.frame)
        self.pidLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pidLabel.setObjectName("pidLabel")
        self.horizontalLayout_3.addWidget(self.pidLabel)
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_3.addWidget(self.line_7)
        self.segLabel = QtWidgets.QLabel(self.frame)
        self.segLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.segLabel.setObjectName("segLabel")
        self.horizontalLayout_3.addWidget(self.segLabel)
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_3.addWidget(self.line_8)
        self.pageLabel = QtWidgets.QLabel(self.frame)
        self.pageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pageLabel.setObjectName("pageLabel")
        self.horizontalLayout_3.addWidget(self.pageLabel)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.proc0 = QtWidgets.QLabel(self.frame)
        self.proc0.setText("")
        self.proc0.setAlignment(QtCore.Qt.AlignCenter)
        self.proc0.setObjectName("proc0")
        self.verticalLayout_2.addWidget(self.proc0)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.proc1 = QtWidgets.QLabel(self.frame)
        self.proc1.setText("")
        self.proc1.setAlignment(QtCore.Qt.AlignCenter)
        self.proc1.setObjectName("proc1")
        self.verticalLayout_2.addWidget(self.proc1)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.proc2 = QtWidgets.QLabel(self.frame)
        self.proc2.setText("")
        self.proc2.setAlignment(QtCore.Qt.AlignCenter)
        self.proc2.setObjectName("proc2")
        self.verticalLayout_2.addWidget(self.proc2)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.proc3 = QtWidgets.QLabel(self.frame)
        self.proc3.setText("")
        self.proc3.setAlignment(QtCore.Qt.AlignCenter)
        self.proc3.setObjectName("proc3")
        self.verticalLayout_2.addWidget(self.proc3)
        self.line_16 = QtWidgets.QFrame(self.frame)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_2.addWidget(self.line_16)
        self.proc4 = QtWidgets.QLabel(self.frame)
        self.proc4.setText("")
        self.proc4.setAlignment(QtCore.Qt.AlignCenter)
        self.proc4.setObjectName("proc4")
        self.verticalLayout_2.addWidget(self.proc4)
        self.line_17 = QtWidgets.QFrame(self.frame)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_2.addWidget(self.line_17)
        self.proc5 = QtWidgets.QLabel(self.frame)
        self.proc5.setText("")
        self.proc5.setAlignment(QtCore.Qt.AlignCenter)
        self.proc5.setObjectName("proc5")
        self.verticalLayout_2.addWidget(self.proc5)
        self.line_18 = QtWidgets.QFrame(self.frame)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_2.addWidget(self.line_18)
        self.proc6 = QtWidgets.QLabel(self.frame)
        self.proc6.setText("")
        self.proc6.setAlignment(QtCore.Qt.AlignCenter)
        self.proc6.setObjectName("proc6")
        self.verticalLayout_2.addWidget(self.proc6)
        self.line_19 = QtWidgets.QFrame(self.frame)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_2.addWidget(self.line_19)
        self.proc7 = QtWidgets.QLabel(self.frame)
        self.proc7.setText("")
        self.proc7.setAlignment(QtCore.Qt.AlignCenter)
        self.proc7.setObjectName("proc7")
        self.verticalLayout_2.addWidget(self.proc7)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame0Label = QtWidgets.QLabel(self.frame)
        self.frame0Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame0Label.setObjectName("frame0Label")
        self.verticalLayout.addWidget(self.frame0Label)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.frame1Label = QtWidgets.QLabel(self.frame)
        self.frame1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame1Label.setObjectName("frame1Label")
        self.verticalLayout.addWidget(self.frame1Label)
        self.line_10 = QtWidgets.QFrame(self.frame)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout.addWidget(self.line_10)
        self.frame2Label = QtWidgets.QLabel(self.frame)
        self.frame2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame2Label.setObjectName("frame2Label")
        self.verticalLayout.addWidget(self.frame2Label)
        self.line_11 = QtWidgets.QFrame(self.frame)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.frame3Label = QtWidgets.QLabel(self.frame)
        self.frame3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame3Label.setObjectName("frame3Label")
        self.verticalLayout.addWidget(self.frame3Label)
        self.line_12 = QtWidgets.QFrame(self.frame)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout.addWidget(self.line_12)
        self.frame4Label = QtWidgets.QLabel(self.frame)
        self.frame4Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame4Label.setObjectName("frame4Label")
        self.verticalLayout.addWidget(self.frame4Label)
        self.line_13 = QtWidgets.QFrame(self.frame)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout.addWidget(self.line_13)
        self.frame5Label = QtWidgets.QLabel(self.frame)
        self.frame5Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame5Label.setObjectName("frame5Label")
        self.verticalLayout.addWidget(self.frame5Label)
        self.line_14 = QtWidgets.QFrame(self.frame)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout.addWidget(self.line_14)
        self.frame6Label = QtWidgets.QLabel(self.frame)
        self.frame6Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame6Label.setObjectName("frame6Label")
        self.verticalLayout.addWidget(self.frame6Label)
        self.line_15 = QtWidgets.QFrame(self.frame)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout.addWidget(self.line_15)
        self.frame7Label = QtWidgets.QLabel(self.frame)
        self.frame7Label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame7Label.setObjectName("frame7Label")
        self.verticalLayout.addWidget(self.frame7Label)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.page0 = QtWidgets.QLabel(self.frame)
        self.page0.setText("")
        self.page0.setAlignment(QtCore.Qt.AlignCenter)
        self.page0.setObjectName("page0")
        self.verticalLayout_4.addWidget(self.page0)
        self.line_27 = QtWidgets.QFrame(self.frame)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.verticalLayout_4.addWidget(self.line_27)
        self.page1 = QtWidgets.QLabel(self.frame)
        self.page1.setText("")
        self.page1.setAlignment(QtCore.Qt.AlignCenter)
        self.page1.setObjectName("page1")
        self.verticalLayout_4.addWidget(self.page1)
        self.line_28 = QtWidgets.QFrame(self.frame)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.verticalLayout_4.addWidget(self.line_28)
        self.page2 = QtWidgets.QLabel(self.frame)
        self.page2.setText("")
        self.page2.setAlignment(QtCore.Qt.AlignCenter)
        self.page2.setObjectName("page2")
        self.verticalLayout_4.addWidget(self.page2)
        self.line_29 = QtWidgets.QFrame(self.frame)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.verticalLayout_4.addWidget(self.line_29)
        self.page3 = QtWidgets.QLabel(self.frame)
        self.page3.setText("")
        self.page3.setAlignment(QtCore.Qt.AlignCenter)
        self.page3.setObjectName("page3")
        self.verticalLayout_4.addWidget(self.page3)
        self.line_30 = QtWidgets.QFrame(self.frame)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.verticalLayout_4.addWidget(self.line_30)
        self.page4 = QtWidgets.QLabel(self.frame)
        self.page4.setText("")
        self.page4.setAlignment(QtCore.Qt.AlignCenter)
        self.page4.setObjectName("page4")
        self.verticalLayout_4.addWidget(self.page4)
        self.line_31 = QtWidgets.QFrame(self.frame)
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.verticalLayout_4.addWidget(self.line_31)
        self.page5 = QtWidgets.QLabel(self.frame)
        self.page5.setText("")
        self.page5.setAlignment(QtCore.Qt.AlignCenter)
        self.page5.setObjectName("page5")
        self.verticalLayout_4.addWidget(self.page5)
        self.line_32 = QtWidgets.QFrame(self.frame)
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.verticalLayout_4.addWidget(self.line_32)
        self.page6 = QtWidgets.QLabel(self.frame)
        self.page6.setText("")
        self.page6.setAlignment(QtCore.Qt.AlignCenter)
        self.page6.setObjectName("page6")
        self.verticalLayout_4.addWidget(self.page6, 0, QtCore.Qt.AlignVCenter)
        self.line_33 = QtWidgets.QFrame(self.frame)
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.verticalLayout_4.addWidget(self.line_33)
        self.page7 = QtWidgets.QLabel(self.frame)
        self.page7.setText("")
        self.page7.setAlignment(QtCore.Qt.AlignCenter)
        self.page7.setObjectName("page7")
        self.verticalLayout_4.addWidget(self.page7)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 6, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.seg0 = QtWidgets.QLabel(self.frame)
        self.seg0.setText("")
        self.seg0.setAlignment(QtCore.Qt.AlignCenter)
        self.seg0.setObjectName("seg0")
        self.verticalLayout_3.addWidget(self.seg0)
        self.line_20 = QtWidgets.QFrame(self.frame)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_3.addWidget(self.line_20)
        self.seg1 = QtWidgets.QLabel(self.frame)
        self.seg1.setText("")
        self.seg1.setAlignment(QtCore.Qt.AlignCenter)
        self.seg1.setObjectName("seg1")
        self.verticalLayout_3.addWidget(self.seg1)
        self.line_21 = QtWidgets.QFrame(self.frame)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_3.addWidget(self.line_21)
        self.seg2 = QtWidgets.QLabel(self.frame)
        self.seg2.setText("")
        self.seg2.setAlignment(QtCore.Qt.AlignCenter)
        self.seg2.setObjectName("seg2")
        self.verticalLayout_3.addWidget(self.seg2)
        self.line_22 = QtWidgets.QFrame(self.frame)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.verticalLayout_3.addWidget(self.line_22)
        self.seg3 = QtWidgets.QLabel(self.frame)
        self.seg3.setText("")
        self.seg3.setAlignment(QtCore.Qt.AlignCenter)
        self.seg3.setObjectName("seg3")
        self.verticalLayout_3.addWidget(self.seg3)
        self.line_23 = QtWidgets.QFrame(self.frame)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout_3.addWidget(self.line_23)
        self.seg4 = QtWidgets.QLabel(self.frame)
        self.seg4.setText("")
        self.seg4.setAlignment(QtCore.Qt.AlignCenter)
        self.seg4.setObjectName("seg4")
        self.verticalLayout_3.addWidget(self.seg4)
        self.line_24 = QtWidgets.QFrame(self.frame)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout_3.addWidget(self.line_24)
        self.seg5 = QtWidgets.QLabel(self.frame)
        self.seg5.setText("")
        self.seg5.setAlignment(QtCore.Qt.AlignCenter)
        self.seg5.setObjectName("seg5")
        self.verticalLayout_3.addWidget(self.seg5)
        self.line_25 = QtWidgets.QFrame(self.frame)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.verticalLayout_3.addWidget(self.line_25)
        self.seg6 = QtWidgets.QLabel(self.frame)
        self.seg6.setText("")
        self.seg6.setAlignment(QtCore.Qt.AlignCenter)
        self.seg6.setObjectName("seg6")
        self.verticalLayout_3.addWidget(self.seg6)
        self.line_26 = QtWidgets.QFrame(self.frame)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.verticalLayout_3.addWidget(self.line_26)
        self.seg7 = QtWidgets.QLabel(self.frame)
        self.seg7.setText("")
        self.seg7.setAlignment(QtCore.Qt.AlignCenter)
        self.seg7.setObjectName("seg7")
        self.verticalLayout_3.addWidget(self.seg7)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 4, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.frame)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 0, 0, 1, 7)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 7)
        self.line_34 = QtWidgets.QFrame(self.frame)
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.gridLayout.addWidget(self.line_34, 1, 1, 1, 1)
        self.line_35 = QtWidgets.QFrame(self.frame)
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout.addWidget(self.line_35, 1, 3, 1, 1)
        self.line_36 = QtWidgets.QFrame(self.frame)
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.gridLayout.addWidget(self.line_36, 1, 5, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backPushButton = QtWidgets.QPushButton(self.frame)
        self.backPushButton.setObjectName("backPushButton")
        self.horizontalLayout.addWidget(self.backPushButton)
        self.nextPushButton = QtWidgets.QPushButton(self.frame)
        self.nextPushButton.setObjectName("nextPushButton")
        self.horizontalLayout.addWidget(self.nextPushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.physMLabel = QtWidgets.QLabel(self.centralwidget)
        self.physMLabel.setGeometry(QtCore.QRect(80, 10, 211, 41))
        self.physMLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.physMLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.physMLabel.setObjectName("physMLabel")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(370, 50, 391, 441))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 371, 421))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_37 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.gridLayout_2.addWidget(self.line_37, 2, 1, 1, 1)
        self.line_38 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.gridLayout_2.addWidget(self.line_38, 1, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.processTable2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.processTable2.setObjectName("processTable2")
        self.verticalLayout_11.addWidget(self.processTable2)
        self.verticalLayout_6.addLayout(self.verticalLayout_11)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.processTable1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.processTable1.setObjectName("processTable1")
        self.verticalLayout_9.addWidget(self.processTable1)
        self.verticalLayout_7.addLayout(self.verticalLayout_9)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.line_40 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.gridLayout_2.addWidget(self.line_40, 1, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.processTable0 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.processTable0.setObjectName("processTable0")
        self.verticalLayout_5.addWidget(self.processTable0)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.processTable3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.processTable3.setObjectName("processTable3")
        self.verticalLayout_10.addWidget(self.processTable3)
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 2, 2, 1, 1)
        self.line_39 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.gridLayout_2.addWidget(self.line_39, 0, 1, 1, 1)
        self.pageTableLabel = QtWidgets.QLabel(self.centralwidget)
        self.pageTableLabel.setGeometry(QtCore.QRect(480, 10, 151, 41))
        self.pageTableLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.pageTableLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pageTableLabel.setObjectName("pageTableLabel")
        self.lineNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.lineNumberLabel.setGeometry(QtCore.QRect(30, 500, 111, 16))
        self.lineNumberLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.lineNumberLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineNumberLabel.setObjectName("lineNumberLabel")
        self.lineNumber = QtWidgets.QLabel(self.centralwidget)
        self.lineNumber.setGeometry(QtCore.QRect(120, 500, 60, 16))
        self.lineNumber.setObjectName("lineNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Trace = QtWidgets.QAction(MainWindow)
        self.actionLoad_Trace.setObjectName("actionLoad_Trace")
        self.actionClear_Screen = QtWidgets.QAction(MainWindow)
        self.actionClear_Screen.setObjectName("actionClear_Screen")
        self.menuFile.addAction(self.actionLoad_Trace)
        self.menuFile.addAction(self.actionClear_Screen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frameLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Frame #</span></p></body></html>"))
        self.pidLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">PID</span></p></body></html>"))
        self.segLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Segment</span></p></body></html>"))
        self.pageLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Page #</span></p></body></html>"))
        self.frame0Label.setText(_translate("MainWindow", "0"))
        self.frame1Label.setText(_translate("MainWindow", "1"))
        self.frame2Label.setText(_translate("MainWindow", "2"))
        self.frame3Label.setText(_translate("MainWindow", "3"))
        self.frame4Label.setText(_translate("MainWindow", "4"))
        self.frame5Label.setText(_translate("MainWindow", "5"))
        self.frame6Label.setText(_translate("MainWindow", "6"))
        self.frame7Label.setText(_translate("MainWindow", "7"))
        self.backPushButton.setText(_translate("MainWindow", "Back"))
        self.nextPushButton.setText(_translate("MainWindow", "Next"))
        self.physMLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Physical Memory</span></p></body></html>"))
        self.processTable2.setText(_translate("MainWindow", "Process 2"))
        self.processTable1.setText(_translate("MainWindow", "Process 1"))
        self.processTable0.setText(_translate("MainWindow", "Process 0"))
        self.processTable3.setText(_translate("MainWindow", "Process 3"))
        self.pageTableLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Page Tables</span></p></body></html>"))
        self.lineNumberLabel.setText(_translate("MainWindow", "Line Number: "))
        self.lineNumber.setText(_translate("MainWindow", "0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Trace.setText(_translate("MainWindow", "Load Trace"))
        self.actionClear_Screen.setText(_translate("MainWindow", "Clear Screen"))
