# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workingGui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.physMLabel = QtWidgets.QLabel(self.centralwidget)
        self.physMLabel.setGeometry(QtCore.QRect(70, 10, 211, 41))
        self.physMLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.physMLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.physMLabel.setObjectName("physMLabel")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(370, 50, 391, 441))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 371, 421))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_37 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.gridLayout_2.addWidget(self.line_37, 2, 1, 1, 1)
        self.line_38 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.gridLayout_2.addWidget(self.line_38, 1, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.processTable1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.processTable1.setText("")
        self.processTable1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.processTable1.setObjectName("processTable1")
        self.verticalLayout_11.addWidget(self.processTable1)
        self.verticalLayout_6.addLayout(self.verticalLayout_11)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.processTable2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.processTable2.setText("")
        self.processTable2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.processTable2.setObjectName("processTable2")
        self.verticalLayout_9.addWidget(self.processTable2)
        self.verticalLayout_7.addLayout(self.verticalLayout_9)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.line_40 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.gridLayout_2.addWidget(self.line_40, 1, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.processTable0 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.processTable0.setAutoFillBackground(False)
        self.processTable0.setStyleSheet("")
        self.processTable0.setText("")
        self.processTable0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.processTable0.setObjectName("processTable0")
        self.verticalLayout_5.addWidget(self.processTable0)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.processTable3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.processTable3.setText("")
        self.processTable3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.processTable3.setObjectName("processTable3")
        self.verticalLayout_10.addWidget(self.processTable3)
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 2, 2, 1, 1)
        self.line_39 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.gridLayout_2.addWidget(self.line_39, 0, 1, 1, 1)
        self.pageTableLabel = QtWidgets.QLabel(self.centralwidget)
        self.pageTableLabel.setGeometry(QtCore.QRect(480, 10, 151, 41))
        self.pageTableLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.pageTableLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pageTableLabel.setObjectName("pageTableLabel")
        self.lineNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.lineNumberLabel.setGeometry(QtCore.QRect(30, 360, 111, 16))
        self.lineNumberLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lineNumberLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineNumberLabel.setObjectName("lineNumberLabel")
        self.lineNumber = QtWidgets.QLabel(self.centralwidget)
        self.lineNumber.setGeometry(QtCore.QRect(120, 360, 60, 16))
        self.lineNumber.setObjectName("lineNumber")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 310, 291, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.backPushButton.setObjectName("backPushButton")
        self.horizontalLayout.addWidget(self.backPushButton)
        self.nextPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.nextPushButton.setObjectName("nextPushButton")
        self.horizontalLayout.addWidget(self.nextPushButton)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(30, 50, 291, 261))
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(74)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.traceFileNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.traceFileNameLabel.setGeometry(QtCore.QRect(30, 400, 71, 16))
        self.traceFileNameLabel.setObjectName("traceFileNameLabel")
        self.traceName = QtWidgets.QLabel(self.centralwidget)
        self.traceName.setGeometry(QtCore.QRect(100, 400, 241, 51))
        self.traceName.setText("")
        self.traceName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.traceName.setWordWrap(True)
        self.traceName.setObjectName("traceName")
        self.lineTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.lineTextLabel.setGeometry(QtCore.QRect(30, 380, 101, 16))
        self.lineTextLabel.setObjectName("lineTextLabel")
        self.lineText = QtWidgets.QLabel(self.centralwidget)
        self.lineText.setGeometry(QtCore.QRect(100, 380, 91, 16))
        self.lineText.setText("")
        self.lineText.setObjectName("lineText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Trace = QtWidgets.QAction(MainWindow)
        self.actionLoad_Trace.setObjectName("actionLoad_Trace")
        self.actionClear_Screen = QtWidgets.QAction(MainWindow)
        self.actionClear_Screen.setObjectName("actionClear_Screen")
        self.menuFile.addAction(self.actionLoad_Trace)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Paging Simulator"))
        self.physMLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Physical Memory</span></p></body></html>"))
        self.pageTableLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Page Tables</span></p></body></html>"))
        self.lineNumberLabel.setText(_translate("MainWindow", "Line Number: "))
        self.lineNumber.setText(_translate("MainWindow", "0"))
        self.backPushButton.setText(_translate("MainWindow", "Back"))
        self.nextPushButton.setText(_translate("MainWindow", "Next"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Frame #"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Segment"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Page #"))
        self.traceFileNameLabel.setText(_translate("MainWindow", "Trace File: "))
        self.lineTextLabel.setText(_translate("MainWindow", "Next Line: "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Trace.setText(_translate("MainWindow", "Load Trace"))
        self.actionClear_Screen.setText(_translate("MainWindow", "Clear Screen"))

